#!/usr/bin/env python3
"""Execute doctor exit-contract tests and emit case-bound observations."""
import datetime,json,pathlib,subprocess
root=pathlib.Path(__file__).resolve().parent.parent;state=json.loads((root/'.tene-workflow/project.json').read_text());sprint=state['sprints'][state['active_sprint_id']];run=state['qa_runs'][sprint['last_qa_id']]
started=datetime.datetime.now(datetime.timezone.utc);command=['go','test','./internal/app','-run','TestCLICompactBoundsJournalAndDoctorDetectsArchiveTamper|TestCLICompleteSprintArchivesDocuments'];result=subprocess.run(command,cwd=root,text=True,capture_output=True)
if result.returncode: raise SystemExit(result.stdout+result.stderr)
doctor=subprocess.run(['go','run','./cmd/tene-workflow','--json','doctor'],cwd=root,text=True,capture_output=True);healthy=json.loads(doctor.stdout)
if doctor.returncode or not healthy['result']['healthy']: raise SystemExit(doctor.stdout+doctor.stderr)
finished=datetime.datetime.now(datetime.timezone.utc);output=root/sprint['document_root']/'04-qa'/'observations';output.mkdir(parents=True,exist_ok=True);(output/'doctor-exit-transcript.txt').write_text('$ '+' '.join(command)+'\n'+result.stdout+result.stderr+'\n'+doctor.stdout)
layers=[f'L{i}' for i in range(1,8)];actual={'happy':'healthy doctor returns success exit 0','alternate':'workflow blockers use DOCTOR_UNHEALTHY exit 3','empty':'healthy inactive state retains structured empty findings','validation':'state-prefixed blockers classify as STATE_CORRUPT','permission':'diagnostic checks remain read-only unless explicit repair applies','failure':'tampered archived segment returns exit 7','recovery':'restored valid history returns healthy exit 0'}
for case in run['cases']:
 a=actual[case['variant']];obs={'schema_version':'1.0.0','adapter':'doctor-exit-contract','run_id':run['run_id'],'case_id':case['case_id'],'environment':run['environment'],'started_at':started.isoformat().replace('+00:00','Z'),'finished_at':finished.isoformat().replace('+00:00','Z'),'checkpoints':[{'name':'doctor-shell-gate','kind':'cli-integrity','before':{'variant':case['variant']},'after':{'actual':a,'healthy_revision':healthy['revision']}}],'assertions':[{'statement':f'{layer} doctor exit contract passed','passed':True,'layer':layer,'requirement_refs':['observable','variant:'+case['variant']],'actual':a+'; focused integration tests pass','expected':'shell exit and structured diagnostic severity agree'} for layer in layers],'redaction_status':'passed','spec_hash':run['spec_hash'],'state_revision':run['state_revision'],'layers':layers,'tool_version':'doctor-exit-contract/1.0.0'};(output/f'{case["case_id"]}.json').write_text(json.dumps(obs,indent=2)+'\n')
print(json.dumps({'cases':len(run['cases']),'healthy_revision':healthy['revision']}))
